version: "3.9"
services:

  neinhorn:
    build: build/docker
    image: zalintyre/neinhorn
    ports:
      - "8080:8080"
    networks:
      - dockernet

  wiremock:
    image: "rodolpheche/wiremock:2.28.1-alpine"
    volumes:
      - "./src/test/wiremock:/home/wiremock:ro"
    ports:
      - "8081:8080"
    networks:
      dockernet:
        aliases:
          - corona-api

networks:
  dockernet:
    driver: bridge
