version: "3.7"
services:

  neinhorn:
    build:
      context: build/docker
      dockerfile: Dockerfile
      args:
        - NEINHORN_VERSION=${NEINHORN_VERSION}
    image: zalintyre/neinhorn:${NEINHORN_VERSION}
    ports:
      - "8080:8080"
    networks:
      - dockernet

  wiremock:
    image: "rodolpheche/wiremock:2.28.1-alpine"
    volumes:
      - "./src/test/wiremock:/home/wiremock:ro"
    ports:
      - "8081:8080"
    networks:
      dockernet:
        aliases:
          - corona-api

networks:
  dockernet:
    driver: bridge
